"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavBarMenu } from "@/components/NavBarMenu";
import { Provider } from "react-redux";
import { store } from "@/redux/store";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
        suppressHydrationWarning
      >
        <Provider store={store}>
          <div className="antialiased min-h-screen w-full dark:bg-black bg-white  dark:bg-grid-white/[0.2] bg-grid-black/[0.2] relative flex items-center justify-center">
            <div className="navbar" style={{ height: 'var(--navbar-height)' }}>
              <NavBarMenu />
            </div>
            {children}
            <div className="h-[50rem]">
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
